### ISSUE TITLE
Docs borrowed from ListView hide the interesting parts

### ISSUE THREAD

**Issue by gnprice** [superlistapp/super_sliver_list#21]
This library is very interesting! I'm beginning to read the code to understand what it's doing.

May I gently suggest *not* copy-pasting the documentation from upstream's ListView and related classes? This is seen currently at today's prerelease version:
https://pub.dev/documentation/super_sliver_list/0.2.0-dev.2/super_sliver_list/SuperListView-class.html
and in main.

This causes two problems:
* Looking at any given piece of documentation, it's hard to be sure whether it's accurate as to `SuperListView`. In many places it currently says `ListView` when it means `SuperListView`, making it clear it's not yet edited for the `SuperListView` context. I figure you'll find and fix those before making a release… but even once you have, it's a lot of text, so it seems like it'll be hard for *you* to be sure you've gone through every line and caught all the more-subtle details that need updating.
* Because it's just a lot of text, it's hard to find the most interesting parts, which are the parts describing how `SuperListView` is different. After all, I already know more or less how `ListView` works; and for details where I don't, I already have a place where I can look them up.

Instead, the strategy I'd recommend is:
* Include as much hand-written documentation as you feel like writing. These docs are great!

* Near the top of the [SuperListView] doc, say something like:
  > The API of [SuperListView] is based on Flutter's [ListView], and most features of the API work exactly the same. For details and examples, see [ListView].

  And repeat the point in a "see also" item at the end.

* Then just leave out all the text that would be copy-pasted.

* Similarly, for the individual constructors and so on, copy just the one summary line at the top, and point to the corresponding ListView constructor. For example for `SuperListView.builder`:
  > Creates a scrollable, linear array of widgets that are created on demand.
  >
  > This constructor corresponds to [ListView.builder]. See there for details on the parameters it has in common.

  Then add anything there is to say about the differences… which I'm not sure there is in this example. `SuperListView.builder` has a few parameters not found on `ListView.builder`, but they correspond directly to fields which have their own docs.

**Comment by knopp** [comment]
I've removed the copied documentation replaced it by references. Admittedly there is still room for improvement.

**Comment by gnprice** [comment]
Looks great, thanks!
