### ISSUE TITLE
The list with sticky headers has performance issue

### ISSUE THREAD

**Issue by amrgetment** [superlistapp/super_sliver_list#22]
While scrolling the list which contains a sticky header it has lagging and slow scrolling even with just 1000 items only
Here is a sample of the live demo

https://github.com/superlistapp/super_sliver_list/assets/149420647/a1c568ee-f49e-4721-aa72-779dcb36efee

**Comment by amrgetment** [comment]
@knopp I opened an issue here, actually most of listviews libraries have performance issue when you add sticky header

**Comment by amrgetment** [comment]
@knopp Wow, it is really very fast 
one missing feature: how to get the first visible item so I can update the side alphabets for contacts list like Google contacts or Samsuang contacts?

Should I open new issue for this feature?

![image](https://github.com/superlistapp/super_sliver_list/assets/149420647/f5f35448-e2eb-40b1-be79-602a04c72654)

**Comment by knopp** [comment]
Please do. That seems like it would be a useful addition.
