### ISSUE TITLE
Horizontal List View

### ISSUE THREAD

**Issue by DarkHeros09** [superlistapp/super_sliver_list#3]
Hi

First of all Thank you for making this package.

is there a way to make a horizontal super sliver list?

**Comment by knopp** [comment]
SuperSliverList should be axis agnostic. Have you tried specifying horizontal axis direction when creating the `CustomScrollView`?

**Comment by DarkHeros09** [comment]
no i did not, but if i have over slivers that i want to be vertical?

thanks for the fast response by the way.
