### ISSUE TITLE
Feature Request: SuperSliverFixedExtentList

### ISSUE THREAD

**Issue by DarkHeros09** [superlistapp/super_sliver_list#4]
Hi 

is it possible to implement this feature?

Thank you.

Great Work btw.

**Comment by knopp** [comment]
What would be the point of this? The whole reason for `SuperSliverList` is to have performant list that can have variable extents. For fixed extents `SliverFixedExtentList` should work just fine with any number of items.

**Comment by DarkHeros09** [comment]
alright thanks.
