### ISSUE TITLE
not find GridView.builder

### ISSUE THREAD

**Issue by wanghuasheng** [superlistapp/super_sliver_list#57]

**Comment by knopp** [comment]
Can you be more specific? How is this related to SuperSliverList?

**Comment by hectorAguero** [comment]
I think more than an issue, is a feature request.

Would be great to have support for GridView and SliverGridView, although the default flutter GridView has other problems also, children width.

**Comment by knopp** [comment]
I'm not sure what the issues are with the `SliverGrid`, but the layout there works different IIRC, the items are not sized depending on their contents, so it shouldn't have same performance issues as the SliverList. It's also out of scope for this package.
